/**
 * Canonical activity log types. These power the Family Timeline and the
 * calm, human labels shown to users.
 */
export const ActivityType = {
  ACCOUNT_CREATED: 'ACCOUNT_CREATED',
  WALLET_LINKED: 'WALLET_LINKED',
  BENEFICIARY_ADDED: 'BENEFICIARY_ADDED',
  BENEFICIARY_UPDATED: 'BENEFICIARY_UPDATED',
  BENEFICIARY_REMOVED: 'BENEFICIARY_REMOVED',
  GUARDIAN_INVITED: 'GUARDIAN_INVITED',
  GUARDIAN_ACCEPTED: 'GUARDIAN_ACCEPTED',
  GUARDIAN_UPDATED: 'GUARDIAN_UPDATED',
  GUARDIAN_REMOVED: 'GUARDIAN_REMOVED',
  ASSET_PROTECTED: 'ASSET_PROTECTED',
  ASSET_UPDATED: 'ASSET_UPDATED',
  ASSET_RELEASED: 'ASSET_RELEASED',
  ASSET_REMOVED: 'ASSET_REMOVED',
  DOCUMENT_UPLOADED: 'DOCUMENT_UPLOADED',
  DOCUMENT_REMOVED: 'DOCUMENT_REMOVED',
  MESSAGE_CREATED: 'MESSAGE_CREATED',
  MESSAGE_UPDATED: 'MESSAGE_UPDATED',
  MESSAGE_REMOVED: 'MESSAGE_REMOVED',
  LEGACY_UPDATED: 'LEGACY_UPDATED',
  LEGACY_PROTECTED: 'LEGACY_PROTECTED',
  LEGACY_VERIFYING: 'LEGACY_VERIFYING',
  LEGACY_RELEASED: 'LEGACY_RELEASED',
  CLAIM_COMPLETED: 'CLAIM_COMPLETED',
  CHECK_IN_CONFIRMED: 'CHECK_IN_CONFIRMED',
  CHECK_IN_MISSED: 'CHECK_IN_MISSED',
} as const;

export type ActivityTypeValue = (typeof ActivityType)[keyof typeof ActivityType];
